### ISSUE TITLE
Can't install gem

### ISSUE THREAD

**Issue by ImaCrea** [rbuchberger/jekyll_picture_tag#178]
Hi there, 
thank you very much for this plugin. It looks just perfect and I can't wait to play with it, unfortunately I can't manager to have is installed.

I'm quite new with gem and bundler so it's very likely I'm doing some mistakes here. I'd really appreciate if you could help.

Here's my gemfile:
```
source "https://rubygems.org"
# gem "rails"
group :jekyll_plugins do
  gem 'jekyll_picture_tag'
end
```

(I'm surprised here there's no mention of _config.yml No need to do anything there?)

Here's what happen when I try **bundle install**
```
Fetching gem metadata from https://rubygems.org/...........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using public_suffix 4.0.5
Using addressable 2.7.0
Using base32 0.3.2
Using bundler 2.1.4
Using colorator 1.1.0
Using concurrent-ruby 1.1.6
Using eventmachine 1.2.7
Fetching http_parser.rb 0.6.0
Installing http_parser.rb 0.6.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
[...]
An error occurred while installing http_parser.rb (0.6.0), and Bundler cannot continue.
Make sure that `gem install http_parser.rb -v '0.6.0' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  jekyll_picture_tag was resolved to 1.10.0, which depends on
    jekyll was resolved to 4.0.1, which depends on
      em-websocket was resolved to 0.5.1, which depends on
        http_parser.rb
```

About context :
```
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
Bundler version 2.1.4
```

Also when I try **jekyll -v** I'm getting a bunch of error :
```
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /usr/local/lib/ruby/gems/2.5.0/specifications/em-websocket-0.5.1.gemspec:15.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /usr/local/lib/ruby/gems/2.5.0/specifications/i18n-0.9.5.gemspec:17.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /usr/local/lib/ruby/gems/2.5.0/specifications/i18n-0.7.0.gemspec:17.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /usr/local/lib/ruby/gems/2.5.0/specifications/rouge-2.2.1.gemspec:18.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /usr/local/lib/ruby/gems/2.5.0/specifications/rouge-1.11.1.gemspec:18.
Traceback (most recent call last):
	15: from /usr/local/bin/jekyll:23:in `<main>'
	14: from /usr/local/bin/jekyll:23:in `load'
	13: from /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-4.0.0/exe/jekyll:11:in `<top (required)>'
	12: from /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-4.0.0/lib/jekyll/plugin_manager.rb:52:in `require_from_bundler'
	11: from /usr/local/lib/ruby/site_ruby/2.5.0/bundler.rb:149:in `setup'
	10: from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:20:in `setup'
	 9: from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/runtime.rb:101:in `block in definition_method'
	 8: from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:226:in `requested_specs'
	 7: from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:237:in `specs_for'
	 6: from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:170:in `specs'
	 5: from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:258:in `resolve'
	 4: from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/resolver.rb:22:in `resolve'
	 3: from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/resolver.rb:49:in `start'
	 2: from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/resolver.rb:258:in `verify_gemfile_dependencies_are_found!'
	 1: from /usr/local/lib/ruby/site_ruby/2.5.0/bundler/resolver.rb:258:in `each'
/usr/local/lib/ruby/site_ruby/2.5.0/bundler/resolver.rb:290:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'jekyll_picture_tag' in any of the gem sources listed in your Gemfile. (Bundler::GemNotFound)
```

More context : the current project I'm working with is supposed to use latest Jekyll *but* on the same computer I'm also working on a jekyll project using github-pages which uses another version of jekyll. I'm affraid this all get mixmatched here between versions and stuff. I guess there's a good way to avoid that and build everything in separated environment nice and safe but I don't know how to that.

Cheers :)

**Comment by rbuchberger** [comment]
You don't have Jekyll in your gemfile? Try adding it: `gem 'jekyll', '~> 4'`
Then try `bundle install` again. When running jekyll commands, prefix them with `bundle exec`, and your dependency problems should go away. Bundler's entire purpose is to manage dependencies, but you need to tell it what those dependencies are. 

I just pushed an update, it's possible I broke something while doing so. If that doesn't work, could you try installing version 1.9? (`gem 'jekyll_picture_tag', '1.9.0' in your gemfile)

> (I'm surprised here there's no mention of _config.yml No need to do anything there?)

Nope! That's a feature :)

**Comment by ImaCrea** [comment]
Thank you for your answer. Please just to have a full example: what do you put in you gemfile ?

**Comment by rbuchberger** [comment]
It should look something like this:

```
source 'https://rubygems.org'

gem 'jekyll', '~> 4'

group :jekyll_plugins do
  gem 'jekyll_picture_tag', '~>1.10'
end
```

Also, after reading your error more closely, this line is important: 

Make sure that `gem install http_parser.rb -v '0.6.0' --source 'https://rubygems.org/'` succeeds before bundling.

**Comment by ImaCrea** [comment]
Thanks! 
Here's what I get when I try **gem install http_parser.rb -v '0.6.0' --source 'https://rubygems.org/'**

```
$ gem install http_parser.rb -v '0.6.0' --source 'https://rubygems.org/'
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /usr/local/lib/ruby/gems/2.5.0/specifications/coffee-script-source-1.11.1.gemspec:16.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /usr/local/lib/ruby/gems/2.5.0/specifications/coffee-script-source-1.10.0.gemspec:16.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /usr/local/lib/ruby/gems/2.5.0/specifications/em-websocket-0.5.1.gemspec:15.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /usr/local/lib/ruby/gems/2.5.0/specifications/i18n-0.9.5.gemspec:17.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /usr/local/lib/ruby/gems/2.5.0/specifications/i18n-0.7.0.gemspec:17.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /usr/local/lib/ruby/gems/2.5.0/specifications/multipart-post-2.0.0.gemspec:17.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /usr/local/lib/ruby/gems/2.5.0/specifications/net-dns-0.8.0.gemspec:16.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /usr/local/lib/ruby/gems/2.5.0/specifications/rouge-2.2.1.gemspec:18.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /usr/local/lib/ruby/gems/2.5.0/specifications/rouge-1.11.1.gemspec:18.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /usr/local/lib/ruby/gems/2.5.0/specifications/sass-3.7.4.gemspec:21.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /usr/local/lib/ruby/gems/2.5.0/specifications/sass-3.4.22.gemspec:19.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /usr/local/lib/ruby/gems/2.5.0/specifications/coffee-script-source-1.11.1.gemspec:16.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /usr/local/lib/ruby/gems/2.5.0/specifications/coffee-script-source-1.10.0.gemspec:16.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /usr/local/lib/ruby/gems/2.5.0/specifications/em-websocket-0.5.1.gemspec:15.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /usr/local/lib/ruby/gems/2.5.0/specifications/i18n-0.9.5.gemspec:17.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /usr/local/lib/ruby/gems/2.5.0/specifications/i18n-0.7.0.gemspec:17.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /usr/local/lib/ruby/gems/2.5.0/specifications/multipart-post-2.0.0.gemspec:17.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /usr/local/lib/ruby/gems/2.5.0/specifications/net-dns-0.8.0.gemspec:16.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /usr/local/lib/ruby/gems/2.5.0/specifications/rouge-2.2.1.gemspec:18.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /usr/local/lib/ruby/gems/2.5.0/specifications/rouge-1.11.1.gemspec:18.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /usr/local/lib/ruby/gems/2.5.0/specifications/sass-3.7.4.gemspec:21.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /usr/local/lib/ruby/gems/2.5.0/specifications/sass-3.4.22.gemspec:19.
Building native extensions. This could take a while...
Successfully installed http_parser.rb-0.6.0
Parsing documentation for http_parser.rb-0.6.0
Done installing documentation for http_parser.rb after 0 seconds
1 gem installed
```

Then I try **bundle install**
```
bundle install --path vendor/bundler
[DEPRECATED] The `--path` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set path 'vendor/bundler'`, and stop using this flag
Fetching gem metadata from https://rubygems.org/...........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using public_suffix 4.0.5
Using addressable 2.7.0
Using base32 0.3.2
Using bundler 2.1.4
Using colorator 1.1.0
Using concurrent-ruby 1.1.6
Using eventmachine 1.2.7
Fetching http_parser.rb 0.6.0
Installing http_parser.rb 0.6.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory: /Users/pcfhstudio/Nextcloud/PCFH
Studio/CLIENTS/IndieHosters/indiehosters-web/vendor/bundler/ruby/2.5.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
/usr/local/opt/ruby/bin/ruby -I /usr/local/lib/ruby/site_ruby/2.5.0 -r ./siteconf20200511-97717-9sdq7u.rb extconf.rb
creating Makefile

current directory: /Users/pcfhstudio/Nextcloud/PCFH
Studio/CLIENTS/IndieHosters/indiehosters-web/vendor/bundler/ruby/2.5.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
make "DESTDIR=" clean

current directory: /Users/pcfhstudio/Nextcloud/PCFH
Studio/CLIENTS/IndieHosters/indiehosters-web/vendor/bundler/ruby/2.5.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
make "DESTDIR="
compiling ruby_http_parser.c
clang: error: no such file or directory:
'Studio/CLIENTS/IndieHosters/indiehosters-web/vendor/bundler/ruby/2.5.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser'
make[1]: *** [ruby_http_parser.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/pcfhstudio/Nextcloud/PCFH
Studio/CLIENTS/IndieHosters/indiehosters-web/vendor/bundler/ruby/2.5.0/gems/http_parser.rb-0.6.0 for inspection.
Results logged to /Users/pcfhstudio/Nextcloud/PCFH
Studio/CLIENTS/IndieHosters/indiehosters-web/vendor/bundler/ruby/2.5.0/extensions/x86_64-darwin-17/2.5.0/http_parser.rb-0.6.0/gem_make.out

An error occurred while installing http_parser.rb (0.6.0), and Bundler cannot continue.
Make sure that `gem install http_parser.rb -v '0.6.0' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  jekyll_picture_tag was resolved to 1.10.0, which depends on
    jekyll was resolved to 4.0.1, which depends on
      em-websocket was resolved to 0.5.1, which depends on
        http_parser.rb
make: *** [install] Error 5
```

I am using a **Makefile** to deploy Jekyll+bootstrap. Here it is as reference :
```
SHELL := /bin/bash
NPM := npm
VENDOR_DIR = assets/vendor/
BUNDLE := bundle
JEKYLL := $(BUNDLE) exec jekyll

PROJECT_DEPS := package.json

.PHONY: all clean install update

all : serve

check:
	$(JEKYLL) doctor
	$(HTMLPROOF) --check-html \
		--http-status-ignore 999 \
		--internal-domains localhost:4000 \
		--assume-extension \
		_site

install: $(PROJECT_DEPS)
	$(NPM) install
	$(BUNDLE) install --path vendor/bundler

update: $(PROJECT_DEPS)
	$(NPM) update
	$(BUNDLE) update

include-npm-deps:
	mkdir -p $(VENDOR_DIR)
	cp node_modules/jquery/dist/jquery.min.js $(VENDOR_DIR)
	cp node_modules/popper.js/dist/umd/popper.min.js $(VENDOR_DIR)
	cp node_modules/bootstrap/dist/js/bootstrap.min.js $(VENDOR_DIR)

build: include-npm-deps
	$(JEKYLL) build

serve: include-npm-deps
	JEKYLL_ENV=production $(JEKYLL) serve
```

**Comment by ImaCrea** [comment]
About the **makefile** I'm following this: https://simpleit.rocks/ruby/jekyll/tutorials/how-to-add-bootstrap-4-to-jekyll-the-right-way/

**Comment by rbuchberger** [comment]
I'm not super smart on bundler, but you're doing odd things with it. I've never had to specify directories manually. I'm sorry to say I don't know the first thing about makefiles; what happens if you directly run `bundle install` (with no other arguments) in your project directory?

**Comment by ImaCrea** [comment]
It looked like it almost worked and then when I installer imagemagick everything seem to got mixed up. And now I'm not able to even start jekyll anymore ^^ Ouch!

Looks like a long night ahead.. I'll let you know next.

**Comment by ImaCrea** [comment]
OK! Looks like it got it to work! 
**Here are the steps I did in order to have it work smoothly on a local build on MacOS Mojave with a Makefile stitching Jekyll 4 and Bootstrap 4 together.** (check this https://simpleit.rocks/ruby/jekyll/tutorials/how-to-add-bootstrap-4-to-jekyll-the-right-way/) cc  @marcanuy

1. I followed that suggestion there first to clean my Ruby installation on Mac. I realized Bundler was not properly working because of that. -> https://stackoverflow.com/questions/51126403/you-dont-have-write-permissions-for-the-library-ruby-gems-2-3-0-directory-ma

2. Ok now we have a proprer Ruby and Bundler installed. Then I do **bundle init** in the repo folder of my jekyll site.

3. I should have a Gemfile now, I open it and replace its content by : 
```
source "https://rubygems.org"

gem 'jekyll', '~> 4'

group :jekyll_plugins do
  gem 'jekyll_picture_tag', '~>1.10'
end
```

4. I update my Makefile in order to take in account **Bundler** :
```
SHELL := /bin/bash
NPM := npm
VENDOR_DIR = assets/vendor/
BUNDLE := bundle
JEKYLL := $(BUNDLE) exec jekyll

PROJECT_DEPS := package.json

.PHONY: all clean install update

all : serve

check:
	$(JEKYLL) doctor
	$(HTMLPROOF) --check-html \
		--http-status-ignore 999 \
		--internal-domains localhost:4000 \
		--assume-extension \
		_site

install: $(PROJECT_DEPS)
	$(NPM) install
	$(BUNDLE) config set path 'vendor/bundler'
	$(BUNDLE) install

update: $(PROJECT_DEPS)
	$(NPM) update
	$(BUNDLE) update

include-npm-deps:
	mkdir -p $(VENDOR_DIR)
	cp node_modules/jquery/dist/jquery.min.js $(VENDOR_DIR)
	cp node_modules/popper.js/dist/umd/popper.min.js $(VENDOR_DIR)
	cp node_modules/bootstrap/dist/js/bootstrap.min.js $(VENDOR_DIR)

build: include-npm-deps
	$(JEKYLL) build

serve: include-npm-deps
	JEKYLL_ENV=production $(JEKYLL) serve
```

5. One step before building all, you need to exclude "vendor" folder from Jekyll. For that, go in **_config.yml** and add **exclude: [vendor]**

6. Now you should be ready to go. Type **make install** and then **make serve**

Also please note, you may have errors popping related to **http_parser.rb 0.6.0** as I had when I started that issue. This is due to spaces in your folders name ! (Took me a while to understand that) So check the path leading to your site folder and make sure no folders got spaces in their name. Then relaunch **make install** and it should work smoothly.

Voilà :) Thank you very much for this gem, I can't wait to play with it now ;)

**Comment by rbuchberger** [comment]
Glad to hear it worked out, and thanks a ton for posting the solution! Hopefully it'll help anyone in the future with similar issues.

Let me know if there's anything else I can do to help!
