### ISSUE TITLE
Crop Fails with 7.0.10 imagemagick

### ISSUE THREAD

**Issue by martinotten** [rbuchberger/jekyll_picture_tag#202]
If I use `crop: 16:9` or probably any option image generation fails. 

I use macOS and 7.0.10 imagemagick. As far as I understood the documentation this version should support cropping?

```
Version: ImageMagick 7.0.10-29 Q16 x86_64 2020-09-06 https://imagemagick.org
Copyright: © 1999-2020 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(3.1)
Delegates (built-in): bzlib freetype gslib heic jng jp2 jpeg lcms lqr ltdl lzma openexr png ps tiff webp xml zlib
```

```
Jekyll Picture Tag Warning: /images/demo/demo-portrait.jpg
is 1000px wide (after cropping, if applicable),
smaller than at least one size in the set [400, 600, 900, 1200, 1600].
Will not enlarge.
  Liquid Exception: `magick identify -format %m %w %h %b /var/folders/l7/lscnxhnd59z7wc0jllr7qh_m0000gn/T/mini_magick20200913-32702-qygal6.jpg[0]` failed with error: identify: unable to open image '/var/folders/l7/lscnxhnd59z7wc0jllr7qh_m0000gn/T/mini_magick20200913-32702-qygal6.jpg': No such file or directory @ error/blob.c/OpenBlob/3537. in index.html
bundler: failed to load command: jekyll (/Users/martinotten/.rbenv/versions/2.7.0/bin/jekyll)
MiniMagick::Error: `magick identify -format %m %w %h %b /var/folders/l7/lscnxhnd59z7wc0jllr7qh_m0000gn/T/mini_magick20200913-32702-qygal6.jpg[0]` failed with error:
identify: unable to open image '/var/folders/l7/lscnxhnd59z7wc0jllr7qh_m0000gn/T/mini_magick20200913-32702-qygal6.jpg': No such file or directory @ error/blob.c/OpenBlob/3537.

  /Users/martinotten/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/mini_magick-4.10.1/lib/mini_magick/shell.rb:17:in `run'
  /Users/martinotten/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/mini_magick-4.10.1/lib/mini_magick/tool.rb:90:in `call'
  /Users/martinotten/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/mini_magick-4.10.1/lib/mini_magick/tool.rb:38:in `new'
  /Users/martinotten/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/mini_magick-4.10.1/lib/mini_magick/image/info.rb:171:in `identify'
  /Users/martinotten/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/mini_magick-4.10.1/lib/mini_magick/image/info.rb:115:in `raw'
  /Users/martinotten/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/mini_magick-4.10.1/lib/mini_magick/image/info.rb:35:in `[]'
  /Users/martinotten/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/mini_magick-4.10.1/lib/mini_magick/image/info.rb:45:in `block in cheap_info'
  /Users/martinotten/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/mini_magick-4.10.1/lib/mini_magick/image/info.rb:44:in `fetch'
  /Users/martinotten/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/mini_magick-4.10.1/lib/mini_magick/image/info.rb:44:in `cheap_info'
  /Users/martinotten/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/mini_magick-4.10.1/lib/mini_magick/image/info.rb:17:in `[]'
  /Users/martinotten/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/mini_magick-4.10.1/lib/mini_magick/image.rb:145:in `block in attribute'
  /Users/martinotten/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/jekyll_picture_tag-1.12.0/lib/jekyll_picture_tag/generated_image.rb:99:in `open_image'
  /Users/martinotten/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/jekyll_picture_tag-1.12.0/lib/jekyll_picture_tag/generated_image.rb:86:in `image'
  /Users/martinotten/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/jekyll_picture_tag-1.12.0/lib/jekyll_picture_tag/generated_image.rb:69:in `update_cache'
  /Users/martinotten/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/jekyll_picture_tag-1.12.0/lib/jekyll_picture_tag/generated_image.rb:46:in `source_width'
  /Users/martinotten/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/jekyll_picture_tag-1.12.0/lib/jekyll_picture_tag/srcsets/basic.rb:90:in `source_width'
  /Users/martinotten/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/jekyll_picture_tag-1.12.0/lib/jekyll_picture_tag/srcsets/basic.rb:77:in `block in checked_targets'
  /Users/martinotten/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/jekyll_picture_tag-1.12.0/lib/jekyll_picture_tag/srcsets/basic.rb:77:in `any?'
  /Users/martinotten/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/jekyll_picture_tag-1.12.0/lib/jekyll_picture_tag/srcsets/basic.rb:77:in `checked_targets'
  /Users/martinotten/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/jekyll_picture_tag-1.12.0/lib/jekyll_picture_tag/srcsets/basic.rb:70:in `build_files'
  /Users/martinotten/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/jekyll_picture_tag-1.12.0/lib/jekyll_picture_tag/srcsets/basic.rb:28:in `files'
  /Users/martinotten/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/jekyll_picture_tag-1.12.0/lib/jekyll_picture_tag/srcsets/basic.rb:32:in `to_a'
  /Users/martinotten/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/jekyll_picture_tag-1.12.0/lib/jekyll_picture_tag/srcsets/basic.rb:36:in `to_s'
```

**Comment by illis** [comment]
Had the same issue. Wrap the 16:9 in quotes and you should be good to go:
`
crop: '16:9'
`

**Comment by rbuchberger** [comment]
I'm sorry that I didn't get to this sooner. I had other stuff going on that took priority. @illis, thanks for the fix!
