### ISSUE TITLE
Ignore SVG 

### ISSUE THREAD

**Issue by felixerdy** [rbuchberger/jekyll_picture_tag#204]
I already noticed that SVGs are not supported. It there a way to ignore SVGs in the configuration?

Here is the output of `bundle exec jekyll serve --trace`

```
Generating new image file: /images/awards/CWA_Logo_2016_M_White-800-1a461bf01.svg
  Liquid Exception: `magick mogrify -auto-orient /var/folders/nn/mxz4g0655l9chn4kmlnrzh300000gn/T/mini_magick20200916-85141-13ej8n5.svg` failed with error: in /_layouts/post.html
Traceback (most recent call last):
	87: from /Users/felix/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:24:in `<main>'
	86: from /Users/felix/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:24:in `eval'
	85: from /Users/felix/.rvm/gems/ruby-2.7.0/bin/jekyll:23:in `<main>'
	84: from /Users/felix/.rvm/gems/ruby-2.7.0/bin/jekyll:23:in `load'
	83: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll-4.0.1/exe/jekyll:15:in `<top (required)>'
	82: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	81: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	80: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	79: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	78: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	77: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll-4.0.1/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
	76: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll-4.0.1/lib/jekyll/command.rb:89:in `process_with_graceful_fail'
	75: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll-4.0.1/lib/jekyll/command.rb:89:in `each'
	74: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll-4.0.1/lib/jekyll/command.rb:89:in `block in process_with_graceful_fail'
	73: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll-4.0.1/lib/jekyll/commands/build.rb:36:in `process'
	72: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll-4.0.1/lib/jekyll/commands/build.rb:65:in `build'
	71: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll-4.0.1/lib/jekyll/command.rb:28:in `process_site'
	70: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll-4.0.1/lib/jekyll/site.rb:76:in `process'
	69: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll-4.0.1/lib/jekyll/site.rb:201:in `render'
	68: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll-4.0.1/lib/jekyll/site.rb:507:in `render_docs'
	67: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll-4.0.1/lib/jekyll/site.rb:507:in `each_value'
	66: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll-4.0.1/lib/jekyll/site.rb:508:in `block in render_docs'
	65: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll-4.0.1/lib/jekyll/site.rb:508:in `each'
	64: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll-4.0.1/lib/jekyll/site.rb:509:in `block (2 levels) in render_docs'
	63: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll-4.0.1/lib/jekyll/site.rb:523:in `render_regenerated'
	62: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll-4.0.1/lib/jekyll/renderer.rb:63:in `run'
	61: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll-4.0.1/lib/jekyll/renderer.rb:89:in `render_document'
	60: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll-4.0.1/lib/jekyll/renderer.rb:159:in `place_in_layouts'
	59: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll-4.0.1/lib/jekyll/renderer.rb:196:in `render_layout'
	58: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll-4.0.1/lib/jekyll/renderer.rb:127:in `render_liquid'
	57: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll-4.0.1/lib/jekyll/liquid_renderer/file.rb:36:in `render!'
	56: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll-4.0.1/lib/jekyll/liquid_renderer/file.rb:70:in `measure_time'
	55: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll-4.0.1/lib/jekyll/liquid_renderer/file.rb:37:in `block in render!'
	54: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll-4.0.1/lib/jekyll/liquid_renderer/file.rb:63:in `measure_bytes'
	53: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll-4.0.1/lib/jekyll/liquid_renderer/file.rb:38:in `block (2 levels) in render!'
	52: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll-4.0.1/lib/jekyll/liquid_renderer/file.rb:59:in `measure_counts'
	51: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll-4.0.1/lib/jekyll/liquid_renderer/file.rb:39:in `block (3 levels) in render!'
	50: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
	49: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
	48: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
	47: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
	46: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:91:in `render'
	45: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
	44: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll-4.0.1/lib/jekyll/tags/include.rb:122:in `render'
	43: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/liquid-4.0.3/lib/liquid/context.rb:123:in `stack'
	42: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll-4.0.1/lib/jekyll/tags/include.rb:125:in `block in render'
	41: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll-4.0.1/lib/jekyll/liquid_renderer/file.rb:36:in `render!'
	40: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll-4.0.1/lib/jekyll/liquid_renderer/file.rb:70:in `measure_time'
	39: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll-4.0.1/lib/jekyll/liquid_renderer/file.rb:37:in `block in render!'
	38: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll-4.0.1/lib/jekyll/liquid_renderer/file.rb:63:in `measure_bytes'
	37: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll-4.0.1/lib/jekyll/liquid_renderer/file.rb:38:in `block (2 levels) in render!'
	36: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll-4.0.1/lib/jekyll/liquid_renderer/file.rb:59:in `measure_counts'
	35: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll-4.0.1/lib/jekyll/liquid_renderer/file.rb:39:in `block (3 levels) in render!'
	34: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
	33: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
	32: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
	31: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
	30: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:82:in `render'
	29: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
	28: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/liquid-4.0.3/lib/liquid/tags/if.rb:43:in `render'
	27: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/liquid-4.0.3/lib/liquid/context.rb:123:in `stack'
	26: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/liquid-4.0.3/lib/liquid/tags/if.rb:44:in `block in render'
	25: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/liquid-4.0.3/lib/liquid/tags/if.rb:44:in `each'
	24: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/liquid-4.0.3/lib/liquid/tags/if.rb:46:in `block (2 levels) in render'
	23: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:82:in `render'
	22: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
	21: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/liquid-4.0.3/lib/liquid/tags/if.rb:43:in `render'
	20: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/liquid-4.0.3/lib/liquid/context.rb:123:in `stack'
	19: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/liquid-4.0.3/lib/liquid/tags/if.rb:44:in `block in render'
	18: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/liquid-4.0.3/lib/liquid/tags/if.rb:44:in `each'
	17: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/liquid-4.0.3/lib/liquid/tags/if.rb:46:in `block (2 levels) in render'
	16: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:91:in `render'
	15: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
	14: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll_picture_tag-1.12.0/lib/jekyll_picture_tag.rb:68:in `render'
	13: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll_picture_tag-1.12.0/lib/jekyll_picture_tag/output_formats/basic.rb:10:in `to_s'
	12: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll_picture_tag-1.12.0/lib/jekyll_picture_tag/output_formats/img.rb:15:in `base_markup'
	11: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll_picture_tag-1.12.0/lib/jekyll_picture_tag/output_formats/basic.rb:21:in `build_base_img'
	10: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll_picture_tag-1.12.0/lib/jekyll_picture_tag/output_formats/basic.rb:84:in `build_fallback_image'
	 9: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll_picture_tag-1.12.0/lib/jekyll_picture_tag/generated_image.rb:23:in `generate'
	 8: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll_picture_tag-1.12.0/lib/jekyll_picture_tag/generated_image.rb:106:in `generate_image'
	 7: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll_picture_tag-1.12.0/lib/jekyll_picture_tag/generated_image.rb:115:in `process_image'
	 6: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll_picture_tag-1.12.0/lib/jekyll_picture_tag/generated_image.rb:86:in `image'
	 5: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/jekyll_picture_tag-1.12.0/lib/jekyll_picture_tag/generated_image.rb:91:in `open_image'
	 4: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/mini_magick-4.10.1/lib/mini_magick/image.rb:457:in `combine_options'
	 3: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/mini_magick-4.10.1/lib/mini_magick/image.rb:577:in `mogrify'
	 2: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/mini_magick-4.10.1/lib/mini_magick/tool.rb:38:in `new'
	 1: from /Users/felix/.rvm/gems/ruby-2.7.0/gems/mini_magick-4.10.1/lib/mini_magick/tool.rb:90:in `call'
/Users/felix/.rvm/gems/ruby-2.7.0/gems/mini_magick-4.10.1/lib/mini_magick/shell.rb:17:in `run': `magick mogrify -auto-orient /var/folders/nn/mxz4g0655l9chn4kmlnrzh300000gn/T/mini_magick20200916-85141-13ej8n5.svg` failed with error: (MiniMagick::Error)
```

**Comment by rbuchberger** [comment]
I've been meaning to add some level of SVG support. For now there's no way to do it, but it's on the todo list. 

Sorry for the slow answer, I had other stuff going on that took priority.

**Comment by felixerdy** [comment]
No worries, thank you!

**Comment by yagarea** [comment]
Hello, is there any progress on this issue ?
