### ISSUE TITLE
vips: 'filesave' is not the name of a vips class

### ISSUE THREAD

**Issue by manz4rk** [rbuchberger/jekyll_picture_tag#280]
EDIT: Just saw the intermediate solution to this in here: https://github.com/rbuchberger/jekyll_picture_tag/issues/279#issuecomment-1200428582
Leaving the issue since the other one is about AVIF, but feel free to merge them @rbuchberger!

Just updated my bundle and all the gems to the latest version, and I am stuck generating the site locally. It all worked before (last time I generated the site was probably around April 2021, so before the v2 (I think).   

Enviroment:
macOS Big Sur 11.6.8
Ruby 3.1.0 from brew
Jekyll 4.2.0
JPT 2.0.3
vips 8.13.0

Did not find mentioned "filesave" anywhere in my workspace.

picture: in _config.yml:
```
picture:
  dimension_attributes: true
  strip: true
  source: _fullsize
  output: img
  ignore_missing_images: true
```

picture.yml:
```
media_queries:
  wide_desktop: "min-width: 1801px"
  desktop: "max-width: 1800px"
  wide_tablet: "max-width: 1200px"
  tablet: "max-width: 900px"
  mobile: "max-width: 600px"

presets:
  default:
    markup: data_auto
    formats: [webp, png]
    widths: [540, 800, 1200, 1920]
    media_widths:
      mobile: [550, 800]
      tablet: [800, 1200]
    sizes:
      mobile: 100vw
      desktop: 60vw
    noscript: true
    dimension_attributes: true
    attributes:
      picture: data-sizes="auto" class="lazyload"
      img: data-sizes="auto" class="lazyload"
    image_options:
      webp:
        lossless: true

  icon:
    base-width: 20
    pixel_ratios: [1, 1.5, 2]

  direct_url:
    formats: [webp, png]
    markup: direct_url
    output_format: direct_url
    dimension_attributes: true
    fallback_width: 1200

  naked_srcset:
    markup: naked_srcset
    dimension_attributes: true
    fallback_width: 1200
```

Log excerpt:
```
Generating new image file: portfolio/The-First-Superhero-poster-540-b56046886.webp
vips: 'filesave' is not the name of a vips class
  Liquid Exception: No support for generating webp files in this environment. in spotthecomposer/index.html
bundler: failed to load command: jekyll (/usr/local/lib/ruby/gems/3.1.0/bin/jekyll)
/usr/local/lib/ruby/gems/3.1.0/gems/jekyll_picture_tag-2.0.3/lib/jekyll_picture_tag/parsers/image_backend.rb:11:in `handler_for': No support for generating webp files in this environment. (RuntimeError)
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll_picture_tag-2.0.3/lib/jekyll_picture_tag/images/image_file.rb:48:in `handler'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll_picture_tag-2.0.3/lib/jekyll_picture_tag/images/image_file.rb:72:in `write'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll_picture_tag-2.0.3/lib/jekyll_picture_tag/images/image_file.rb:35:in `build'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll_picture_tag-2.0.3/lib/jekyll_picture_tag/images/image_file.rb:19:in `initialize'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll_picture_tag-2.0.3/lib/jekyll_picture_tag/images/generated_image.rb:81:in `new'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll_picture_tag-2.0.3/lib/jekyll_picture_tag/images/generated_image.rb:81:in `generate_image'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll_picture_tag-2.0.3/lib/jekyll_picture_tag/images/generated_image.rb:25:in `generate'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll_picture_tag-2.0.3/lib/jekyll_picture_tag/srcsets/basic.rb:71:in `each'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll_picture_tag-2.0.3/lib/jekyll_picture_tag/srcsets/basic.rb:71:in `build_files'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll_picture_tag-2.0.3/lib/jekyll_picture_tag/srcsets/basic.rb:28:in `files'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll_picture_tag-2.0.3/lib/jekyll_picture_tag/srcsets/basic.rb:32:in `to_a'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll_picture_tag-2.0.3/lib/jekyll_picture_tag/srcsets/basic.rb:36:in `to_s'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll_picture_tag-2.0.3/lib/jekyll_picture_tag/output_formats/data_attributes.rb:17:in `add_srcset'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll_picture_tag-2.0.3/lib/jekyll_picture_tag/output_formats/picture.rb:39:in `build_source'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll_picture_tag-2.0.3/lib/jekyll_picture_tag/output_formats/picture.rb:26:in `block in build_sources'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll_picture_tag-2.0.3/lib/jekyll_picture_tag/output_formats/picture.rb:26:in `collect'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll_picture_tag-2.0.3/lib/jekyll_picture_tag/output_formats/picture.rb:26:in `build_sources'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll_picture_tag-2.0.3/lib/jekyll_picture_tag/output_formats/picture.rb:66:in `base_markup'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll_picture_tag-2.0.3/lib/jekyll_picture_tag/output_formats/data_attributes.rb:7:in `base_markup'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll_picture_tag-2.0.3/lib/jekyll_picture_tag/output_formats/basic.rb:10:in `to_s'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll_picture_tag-2.0.3/lib/jekyll_picture_tag.rb:71:in `render'
        from /usr/local/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
        from /usr/local/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:91:in `render'
        from /usr/local/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
        from /usr/local/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
        from /usr/local/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
        from /usr/local/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:39:in `block (3 levels) in render!'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:59:in `measure_counts'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:38:in `block (2 levels) in render!'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:63:in `measure_bytes'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:37:in `block in render!'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:70:in `measure_time'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:36:in `render!'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll-4.2.0/lib/jekyll/inclusion.rb:16:in `render'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll-4.2.0/lib/jekyll/tags/include.rb:208:in `block in render'
        from /usr/local/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/context.rb:123:in `stack'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll-4.2.0/lib/jekyll/tags/include.rb:206:in `render'
        from /usr/local/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
        from /usr/local/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:91:in `render'
        from /usr/local/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
        from /usr/local/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
        from /usr/local/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
        from /usr/local/lib/ruby/gems/3.1.0/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:39:in `block (3 levels) in render!'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:59:in `measure_counts'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:38:in `block (2 levels) in render!'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:63:in `measure_bytes'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:37:in `block in render!'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:70:in `measure_time'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll-4.2.0/lib/jekyll/liquid_renderer/file.rb:36:in `render!'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll-4.2.0/lib/jekyll/renderer.rb:131:in `render_liquid'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll-4.2.0/lib/jekyll/renderer.rb:80:in `render_document'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll-4.2.0/lib/jekyll/renderer.rb:63:in `run'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:547:in `render_regenerated'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:539:in `block in render_pages'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:538:in `each'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:538:in `render_pages'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:211:in `render'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll-4.2.0/lib/jekyll/site.rb:80:in `process'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:28:in `process_site'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:65:in `build'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:36:in `process'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `each'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll-4.2.0/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll-4.2.0/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
        from /usr/local/lib/ruby/gems/3.1.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from /usr/local/lib/ruby/gems/3.1.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from /usr/local/lib/ruby/gems/3.1.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from /usr/local/lib/ruby/gems/3.1.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from /usr/local/lib/ruby/gems/3.1.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from /usr/local/lib/ruby/gems/3.1.0/gems/jekyll-4.2.0/exe/jekyll:15:in `<top (required)>'
        from /usr/local/lib/ruby/gems/3.1.0/bin/jekyll:25:in `load'
        from /usr/local/lib/ruby/gems/3.1.0/bin/jekyll:25:in `<top (required)>'
        from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.2.15/lib/bundler/cli/exec.rb:63:in `load'
        from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.2.15/lib/bundler/cli/exec.rb:63:in `kernel_load'
        from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.2.15/lib/bundler/cli/exec.rb:28:in `run'
        from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.2.15/lib/bundler/cli.rb:494:in `exec'
        from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.2.15/lib/bundler/cli.rb:30:in `dispatch'
        from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.2.15/lib/bundler/cli.rb:24:in `start'
        from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.2.15/exe/bundle:49:in `block in <top (required)>'
        from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.2.15/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
        from /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.2.15/exe/bundle:37:in `<top (required)>'
        from /usr/local/opt/ruby/bin/bundle:25:in `load'
        from /usr/local/opt/ruby/bin/bundle:25:in `<main>'
```

**Comment by stuntbox** [comment]
@rbuchberger Just wanted to say thank you for this fix! I got hit with the same exact issue returning to a side project after many months + a switch to Apple Silicon.
